"""update transactions table

Revision ID: 05ddb85711c3
Revises: 6f25321b2d5e
Create Date: 2025-12-13 01:35:44.421860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ddb85711c3'
down_revision: Union[str, Sequence[str], None] = '6f25321b2d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('creditor_name', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('debtor_name', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('uq_bank_account_transaction'), 'transactions', type_='unique')
    op.drop_column('transactions', 'transaction_type')
    op.drop_column('transactions', 'encrypted_description')
    op.drop_column('transactions', 'encrypted_creditor_name')
    op.drop_column('transactions', 'transaction_id')
    op.drop_column('transactions', 'encrypted_debtor_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('encrypted_debtor_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('encrypted_creditor_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('encrypted_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_bank_account_transaction'), 'transactions', ['bank_account_id', 'transaction_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('transactions', 'debtor_name')
    op.drop_column('transactions', 'creditor_name')
    # ### end Alembic commands ###
