"""stop using enums in bankaccount

Revision ID: 6f25321b2d5e
Revises: 17d3af435f87
Create Date: 2025-12-13 00:50:39.757264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f25321b2d5e'
down_revision: Union[str, Sequence[str], None] = '17d3af435f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'bank_provider',
               existing_type=postgresql.ENUM('vpbank', name='bankprovider'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'bank_provider',
               existing_type=sa.String(),
               type_=postgresql.ENUM('vpbank', name='bankprovider'),
               existing_nullable=False)
    # ### end Alembic commands ###
